---
title: "Analisis de datos de COVID-19 en Costa Rica - Gráficos del paquete base"
author: "Juan Alberto Mora"
date: '2022-05-11'
output:
  html_document:
    theme: readable    
    toc: true
    toc_depth: 5
    toc_float:
      collapsed: false
      smooth_scroll: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Presentación

Este documento presenta gráficos generados a partir de los datos de COVID-19 en Costa Rica compartidos por el Ministerio de Salud en <https://geovision.uned.ac.cr/oges/>

## Entradas

```{r carga-datos}
covid <- read.csv(file="05_10_22_CSV_GENERAL.csv", sep = ";")
```

## Procesamiento

## Opciones Generales

```{r ociones-generales}
options(scipen = 7)
```


### Curación de datos
```{r conversión-fecha}
covid$FECHA <- as.Date(covid$FECHA, format = "%d/%m/%Y")
```

## Salidas

### Gráficos

#### Casos acumulados

##### Positivos

```{r casos-positivos-acumulados}
plot(
  covid$FECHA,
  covid$positivos,
  type = "l",
  xaxt = "n",
  yaxt = "n",
  main = "Casos acumulados positivos de COVID-19 en Costa Rica",
  xlab = "Fecha",
  ylab = "Casos"
)

### Formato del eje X

axis(
  side = 1,
  covid$FECHA,
  tick = FALSE,
  format(covid$FECHA, "%m-%y"),
  cex.axis = .7
)

### Formato del eje Y
axis(
  side = 2,
  covid$positivos,
  labels = TRUE,  
  at = seq(0, 1000000, by = 200000),
  cex.axis = .7
)
```

##### Fallecidos

```{r casos-Fallecidos-acumulados}
plot(
  covid$FECHA,
  covid$fallecidos,
  type = "l",
  xaxt = "n",
  yaxt = "n",
  main = "Casos acumulados fallecidos de COVID-19 en Costa Rica",
  xlab = "Fecha",
  ylab = "Muertes"
)

### Formato del eje X

axis(
  side = 1,
  covid$FECHA,
  tick = FALSE,
  format(covid$FECHA, "%m-%y"),
  cex.axis = .7
)

### Formato del eje Y
axis(
  side = 2,
  covid$fallecidos,
  labels = TRUE,  
  at = seq(0, 10000, by = 2000),
  cex.axis = .7
)
```

##### Otros

```{r casos_otros_acumulados}
plot(
  covid$FECHA,
  covid$positivos,
  type = "l",
  xaxt = "n",
  yaxt = "n",
  main = "Casos acumulados de COVID-19 en Costa Rica",
  xlab = "Fecha",
  ylab = "Casos",
  col= "blue"
)

# Casos Activos

lines(covid$FECHA, covid$activos, col= "red")

lines(covid$FECHA, covid$RECUPERADOS, col= "green")

lines(covid$FECHA, covid$fallecidos, col= "black")

# Leyenda

legend(
  x = "topleft",
  inset = 0.03,
  legend = c("Positivos", "Activos", "Recuperados", "Fallecidos"),
  col = c("blue", "red", "green", "black"),
  lty = 1,
  cex = 0.7)

# Formato del eje X
axis(side = 1,
     covid$FECHA,
     tick = FALSE,
     format(covid$FECHA, "%m-%y"),
     cex.axis = .7)
# Formato del eje Y
axis(
  side = 2,
  covid$positivos,
  labels = TRUE,  
  at = seq(0, 1000000, by = 200000),
  cex.axis = .7
)
```

#### Casos diarios

##### Positivos

```{r casos-positivos}
# Gráfico de barras
barplot(
  height=covid$nue_posi,
  names.arg=format(covid$FECHA, "%Y"),
  ann = FALSE, 
  bty = "n", 
  tck = 0, 
  xaxt = "n",
  space = 1,
  main="Casos positivos por día",
  xlab = "Fecha",
  ylab = "Casos positivos",
  col = "blue"
)

# Fechas minima y máxima
x_min <- min(covid$FECHA)
x_max <- max(covid$FECHA)

# Formato del eje X
axis(
  side = 1,
  at = match(seq(as.Date(x_min), x_max, "years"), covid$FECHA) * (1 + 1),
  labels = format(seq(as.Date(x_min), x_max, "years"), "%Y"),
  lwd = 0)
```
##### Fallecidos

```{r casos-fallecidos}
# Gráfico de barras
barplot(
  height=covid$nue_falleci,
  names.arg=format(covid$FECHA, "%Y"),
  ann = FALSE, 
  bty = "n", 
  tck = 0, 
  xaxt = "n",
  space = 1,
  main="Casos fallecidos por día",
  xlab = "Fecha",
  ylab = "Casos fallecidos",
  col = "black"
)

# Fechas minima y máxima
x_min <- min(covid$FECHA)
x_max <- max(covid$FECHA)

# Formato del eje X
axis(
  side = 1,
  at = match(seq(as.Date(x_min), x_max, "years"), covid$FECHA) * (1 + 1),
  labels = format(seq(as.Date(x_min), x_max, "years"), "%Y"),
  lwd = 0)
```

